server:
  port: 8081
spring:
  datasource:
    url: "jdbc:h2:file:~/surveys;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
  mvc:
    servlet:
      path: "/api/v1"
  web:
    resources:
      # TODO in docker map to a volume
      static-locations: "file:/Users/antongoncharov/GitRepositories/personal/kotlin-vue-surveys-demo/jvm/src/main/resources/static/"

jwt:
  secret: "p2FpI17UQx3Z+RRyvFfigMUDGaBkhLgB30NXrbn/NANW2//u/eVzQwSFYxQEpZHeQ0audHPXyiRHiDER0oQqPGDGgvnaLJiJ3g/HuEo34hj/FmNh7LpR/1NFUiYtcOl0qAgfWZee+OtUCtpWnuxlS3BrybIvqqNmzQOMMGowN+aWeuE451J/CAGNXqwQLQkCXmpTG7HeOU4JJ6gRg9qvgEMSoJSIwg1I3eXgPA=="


app:
  imageStore:
    # TODO in docker map to a volume
    path: "/Users/antongoncharov/GitRepositories/personal/kotlin-vue-surveys-demo/jvm/src/main/resources/static/uploads"